In [1]:

import numpy as np

In [2]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(np.min(stats))

1


In [6]:
np.min(stats, axis=1)

array([1, 4])

In [7]:
np.min(stats, axis=0)

array([1, 2, 3])

In [8]:
np.max(stats, axis=1)

array([3, 6])

In [11]:
print(np.sum(stats))


21


In [14]:
# Students scores
scores = np.array([10, 14, 12, 18, 16, 15, 9, 19])

print("Avg Score:", np.mean(scores))
print("Best Score:", np.max(scores))
print("Lowest Score:", np.min(scores))
print("Median Score:", np.median(scores))
print("Std Dev:", np.std(scores))

Avg Score: 14.125
Best Score: 19
Lowest Score: 9
Median Score: 14.5
Std Dev: 3.370367190678191


| Function   | Purpose             |
| ---------- | ------------------- |
| `sum()`    | Total of all values |
| `mean()`   | Average             |
| `min()`    | Smallest value      |
| `max()`    | Largest value       |
| `median()` | Middle value        |
| `std()`    | Spread / variation  |
