In [1]:

import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

![Matrix](https://screendy-cdn.fra1.cdn.digitaloceanspaces.com/platfrom-v2/_files/file_1761610457653_Oct282025Screenshot4.png)

![](https://screendy-cdn.fra1.cdn.digitaloceanspaces.com/platfrom-v2/_files/file_1761610527330_Width1600.webp)

![](https://screendy-cdn.fra1.cdn.digitaloceanspaces.com/platfrom-v2/_files/file_1761613307905_Oct282025Screenshot5.png)

![](https://screendy-cdn.fra1.cdn.digitaloceanspaces.com/platfrom-v2/_files/file_1761613763474_Screenshot2025-10-28at020901.png)

https://www.youtube.com/watch?v=rHLEWRxRGiM

In [7]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [8]:
# Calculate profit by subtracting expenses from revenue
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [10]:
# Calculate total sales from units and price per unit using broadcasting
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
print(units * price_per_unit)

[[30000 16000 60000]
 [ 5000  4000 18000]
 [ 2000  2000  8400]]


In [11]:
# Correct way is matrix multiplication using dot product
total_sales = np.dot(price_per_unit, units)
total_sales

array([34400, 50000, 64400])

| Concept                         | Meaning                                        |
| ------------------------------- | ---------------------------------------------- |
| `profit = revenue - expenses`   | Element-wise subtraction                       |
| `price_per_unit * units`        | Broadcasting (wrong for matrix multiplication) |
| `np.dot(price_per_unit, units)` | Real matrix multiplication (correct)           |


In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]]) 

In [18]:
print(A)
print(B)
print("A@B: ", A@B)
print("np.matmul(A,B): ", np.matmul(A,B))
print("np.dot(A,B): ", np.dot(A,B))



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
A@B:  [[19 22]
 [43 50]]
np.matmul(A,B):  [[19 22]
 [43 50]]
np.dot(A,B):  [[19 22]
 [43 50]]


In [24]:
A = np.ones((3, 2, 3))      # 3 matrices, each 2x3
B = np.full((3, 3, 2), 2)  
print(A)
print("-"*10)
print(B)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
----------
[[[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]]]


In [25]:
print("-"*10)
print(np.matmul(A,B))

----------
[[[6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]]]


In [26]:
print("-"*10)
print(A@B)


----------
[[[6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]]]


In [31]:

c = np.identity(3)
print(c)
print("-"*10)
# Find the determinant
print(np.linalg.det(c))




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------
1.0
