In [2]:

import numpy as np


In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Dimension
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [7]:
# Get Shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size in bytes , because each element is 4 bytes (int32).
a.itemsize

4