Accessing/Changing specific elements, rows, columns, etc


In [1]:

import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# Get a specific element [r, c]
print(a[1, 5])


13


In [5]:
# Get a specific element [r, c]
print(a[1, -2])

13


In [8]:

# Get a specific row 
print(a[0, :])

[1 2 3 4 5 6 7]


In [9]:

# Get a specific column
print(a[:, 2])

[ 3 10]


In [10]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])



[2 4 6]


In [12]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:-1:2])



[2 4 6]


![](https://screendy-cdn.fra1.cdn.digitaloceanspaces.com/platfrom-v2/_files/file_1761614650114_Oct282025Screenshot6.png)

In [13]:
a[1,5] = 20
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [14]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [15]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
print(b[0,1,1])

4


In [18]:
# Get specific element (work outside in)
print(b[:,1,:])

[[3 4]
 [7 8]]


In [20]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [21]:
# replace Error 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.