Initializing Different Types of Arrays

In [1]:

import numpy as np

In [2]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.zeros((2,3,3), dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [ ]:
np.zeros((2,3,3,2), dtype='int32') # 4d array

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]], dtype=int32)

In [7]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [8]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
# Any other number
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [12]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.42785881, 0.41101272],
       [0.77869359, 0.12792627],
       [0.78150392, 0.93155284],
       [0.79481498, 0.9765674 ]])

In [13]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.62655893, 0.33623052, 0.14901028, 0.45511923, 0.40525471,
        0.61946757, 0.3698135 ],
       [0.70815429, 0.8473191 , 0.75173464, 0.55435699, 0.54347028,
        0.7254325 , 0.45207462]])

In [14]:
# Random Integer values (range 0-7)
np.random.randint(7, size=(3,3))

array([[2, 3, 3],
       [5, 4, 2],
       [1, 6, 3]])

In [15]:
# Random Integer values (range 4-7)
np.random.randint(4, 7, size=(3,3))



array([[5, 5, 5],
       [4, 6, 4],
       [5, 6, 4]])

In [17]:
# Random Integer values (range -4-7)
np.random.randint(-4, 7, size=(3,3))



array([[ 2,  4,  0],
       [ 0,  1,  4],
       [-1,  4,  0]])

In [ ]:
# The identity matrix - square matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# The identity matrix - square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)



[1 1 1 2 2 2 3 3 3]


In [22]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


![](https://screendy-cdn.fra1.cdn.digitaloceanspaces.com/platfrom-v2/_files/file_1761609678124_Oct282025Screenshot3.png)

In [24]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [27]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!!!

In [28]:
a = np.array([1,2,3])
b = a
b[0] = 100

print("a: ", a)
print("b: ", b)



a:  [100   2   3]
b:  [100   2   3]


In [29]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print("a: ", a)
print("b: ", b)

a:  [1 2 3]
b:  [100   2   3]
